services:
  - type: web
    name: sat-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node api/server.js
    envVars:
      - key: NODE_ENV
        value: production
